version: '3'
services:
  app:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: